### ISSUE TITLE
Fallback to IPv4 if IPv6 is enabled but no connection can be established

### ISSUE THREAD

**Issue by evgeni** [pokerth/pokerth#276]
From: [Debian Bug #740356](http://bugs.debian.org/740356)
Version: 1.1.1

When I have `InternetServerUseIpv6=1` in my config, but no IPv6 connectivity at all, internet games fail with "The server name could not be resolved." after pressing the "internet game" button. If I enable teredo tunneling (using the miredo package), I get either "The connection to the server was lost." or "Connection timed out.". Internet games work just fine over IPv6, when I am connected to my "normal" (HE.net provided) IPv6 tunnel.

I think enabling IPv6 should not mean IPv4 is disabled and the connection should fall back to IPv4 if there was a problem connecting over v6.

**Comment by lotodore** [comment]
As there was no more feedback, I'm closing this issue. Please reopen if you'd suggest a different solution.

**Comment by Roger-WIN** [comment]
I have used [http://ipv6-test.com/](url) and it said that my browser didn't  support fallback, even though I was using the latest Google Chrome and Windows 10. The current situation is that some websites can't be accessed after I enable IPv6. I think that's because they don't support IPv6. And now I don't know what to do.

**Comment by q4z1** [comment]
@Roger-WIN : I am not sure how this is related to the pokerth client.
The current game-server provider does not support ipv6 at the moment - so you have to disable ipv6 in the game client.
