### ISSUE TITLE
Weird login behavior

### ISSUE THREAD

**Issue by joaopaulops93** [pokerth/pokerth#399]
I have the application installed in a Windows machine and I'm able to login and play with my username successfully, but when I try to login as a member in the website it shows a message saying that the username and password don't match or I do not have an account yet.

**Comment by q4z1** [comment]
Hey,

you should try to use the password reset/forgot password feature in order to get you passwords (forum and game-client) synchronized. If you have a forum account older than end of 2016, the passwords might be not synchronized - that was implemented a bit later.

If that is not a possible reason - please give me your username - I will make some checks then.


Regards.

**Comment by andy5995** [comment]
I just tried logging in with pokerth and I got the message that my account has been blocked indefinitely. Is this a known issue?

I was able to log in and played a game earlier today, and 2 last night and everything worked great.

I'm still able to log in to the website. My username is 'archstanton'
